name: Run Tests

on:
  push:
    branches: [ main, feliz_v3.0 ]
  pull_request:
    branches: [ main, feliz_v3.0 ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # or whatever version you need

    #   - name: Setup Node.js and NPM
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: '20'  # or another version if needed
    #       cache: 'npm'

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.5

      - name: Install dependencies
        run: bun install

      - name: run tests
        run: npm test
